services:
  spark-runtime:
    image: bitnami/spark:3.5.1
    container_name: taxi-spark-runtime
    working_dir: /workspace
    command: ["bash", "-lc", "sleep infinity"]
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=127.0.0.1
      - SPARK_MASTER_HOST=spark-runtime
      - SPARK_DRIVER_BIND_ADDRESS=0.0.0.0
      - HADOOP_CONF_DIR=/opt/bitnami/spark/conf
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/workspace
      - spark-warehouse:/tmp/spark-warehouse
    ports:
      - "4040:4040"
    networks:
      - taxi-network

volumes:
  spark-warehouse:

networks:
  taxi-network:
    driver: bridge
